### ISSUE TITLE
go run fails

### ISSUE THREAD

**Issue by joeblew99** [hasit/bolter#11] opened 2017-05-14 23:49 UTC
````
x-MacBook-Pro:go apple$ cd $GOPATH/src/github.com/hasit/bolter
x-MacBook-Pro:bolter apple$ ls
LICENSE		README.md	assets		bolter.go	sample-db
x-MacBook-Pro:bolter apple$ go run bolter.go 
# command-line-arguments
./bolter.go:70: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment
x-MacBook-Pro:bolter apple$ go build
# github.com/hasit/bolter
./bolter.go:70: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment
x-MacBook-Pro:bolter apple$ go build bolter.go 
# command-line-arguments
./bolter.go:70: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment

````

**Comment by hasit** [comment] 2017-05-15 07:39
@joeblew99 

Thank you for posting the issue.  I tried to retrace your steps and it compiles fine on my machine.

``` fish
 g/s/g/h/bolter ╍ ls
LICENSE   README.md assets    bolter.go sample-db
 g/s/g/h/bolter ╍ go run bolter.go
NAME:
  bolter - view boltdb file interactively in your terminal

VERSION:
  2.0.0

USAGE:
  bolter [global options]

GLOBAL OPTIONS:
  --file FILE, -f FILE  boltdb FILE to view
  --help, -h            show help
  --version, -v         print the version

AUTHOR:
  Hasit Mistry <hasitnm@gmail.com>
COPYRIGHT:
  (c) 2016 Hasit Mistry
 g/s/g/h/bolter ╍ go build                                                   (417ms)
 g/s/g/h/bolter ╍ ls                                                         (425ms)
LICENSE   README.md assets    bolter    bolter.go sample-db
 g/s/g/h/bolter ╍
```

Let us try to fix it as soon as possible for you. Can you tell me the output of `go version` in the meanwhile?

**Comment by joeblew99** [comment] 2017-05-15 07:48
thanks for helping

x-MacBook-Pro:bolthold apple$ go version

go version go1.8.1 darwin/amd64

**Comment by hasit** [comment] 2017-05-15 16:39
@joeblew99 

I cannot exactly pin the cause of the problem since I cannot reproduce it. After bit of digging, I believe the issue is related to dependencies. Can you try running `go get -u github.com/hasit/bolter` instead of normal `go get`? Let me know if that works.

**Comment by ross-spencer** [comment] 2017-05-26 11:15
I'm looking on go version go1.8.1 linux/amd64 as well. Looks good here.

**Comment by hasit** [comment] 2017-05-26 21:30
@ross-spencer 

Thank you for confirming.

**Comment by hasit** [comment] 2017-06-30 21:43
@joeblew99 

Hello, is your issue resolved? Let us know if it is still not working and we find a solution for you.

**Comment by joeblew99** [comment] 2017-07-02 20:09
hey @hasit 

here we go 

````
x-MacBook-Pro:hasit apple$ cd $GOPATH
x-MacBook-Pro:go apple$ go get -u -v  github.com/hasit/bolter
github.com/hasit/bolter (download)
github.com/codegangsta/cli (download)
# cd /Users/apple/workspace/go/src/github.com/codegangsta/cli; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/codegangsta/cli: exit status 1
github.com/kval-access-language/kval-boltdb (download)
github.com/boltdb/bolt (download)
github.com/kval-access-language/kval-parse (download)
github.com/kval-access-language/kval-scanner (download)
github.com/pkg/errors (download)
github.com/olekukonko/tablewriter (download)
github.com/mattn/go-runewidth (download)
x-MacBook-Pro:go apple$ cd $GOPATH/src/github.com/hasit/bolter
x-MacBook-Pro:bolter apple$ go build
# github.com/hasit/bolter
./bolter.go:70: cannot use func literal (type func(*cli.Context) error) as type func(*cli.Context) in assignment

````

i did not look into the reason why it is failing..

**Comment by hasit** [comment] 2017-07-03 15:56
@joeblew99 

I have updated the dependencies and committed the change. `github.com/codegangsta/cli` no longer exists and is now `github.com/urfave/cli`. Please check and tell me if it works now.

**Closed** 2019-11-20 18:15 UTC

**Comment by Rafaela314** [comment] 2020-01-09 14:37
I have the same issue. got get -u ... does not work for me. I ge the message:
go/src/github.com/hasit/bolter/bolter.go:43:14: cannot use []cli.Author literal (type []cli.Author) as type []*cli.Author in assignment
../go/src/github.com/hasit/bolter/bolter.go:51:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
	cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)

**Comment by gslin** [comment] 2023-07-17 18:27
It looks like lengrongfu has patched this issue in his fork https://github.com/lengrongfu/bolter.
